### ISSUE TITLE
outspectra flag not working as of v2.03

### ISSUE THREAD

**Issue by avoyles** [arjankoning1/talys#4]
Hi Arjan,

For a simple test file after building v2.04, I noticed that the `outspectra y` flag in an input file was not actually producing any of the outgoing composite particle spectra as intended.  The test file used was:

```
#
# General
#
projectile d
element Cu
mass 0
energy 1 40 1
#
# Output
#
outspectra          y
```

The particle spectra were not output even with multiple variations on mass, energy, element, and projectile. 

I went and checked out prior commits for v2.00, v2.01, v2.02, v2.03, v2.04, and the most recent commit.  Using the same input file across all 6 versions, particle spectra are output in 2.00, 2.01, and 2.02, as of commit 65b2dc874dbd32d3ed649287ec35ed2edae3ba90.  

However, starting in v2.03 (commit d5703833e0434ac69251721e6237218632cc37d5), the output file instead returns:

```
 7. Composite particle spectra

 Spectra for outgoing gamma   


 Spectra for outgoing neutron 


 Spectra for outgoing proton  


 Spectra for outgoing deuteron


 Spectra for outgoing helium-3


 Spectra for outgoing alpha   


 Average emission energies
```

when running both a single energy, or a multi-energy input file.  This behavior remains in both v2.04 (commit d269fa215357f80b6c7566cab7fa516d6f41a0b9), as well as the current commit (aa4753c0e02cb732de6580e8b3b58a14fc7521ee).  

I'm not sure exactly what happened, but my best guess is that in between these commits, lines 111-132 of source/spectraout.f90 were deleted - this seems to control the writing of these composite spectra to the output file. A new line 156 

```
write(*, '(/" LAB spectra for outgoing ", a8/)') parname(type)
```

was added for Lab spectra, but no equivalent version of the composite particle spectra seems to have been added ti replace the writing block which was removed.

Any help with a patch ehre would be greatly appreciated. Thanks!

**Comment by arjankoning1** [comment]
Hi Andrew,
  Latest version should have solved this. As you may have noticed, I am making all the output of TALYS more uniform, with consistent Metadata etc. to enable more automated processing for AI/L, processing codes etc and sometimes this goes wrong, apparently. Instead of printing everything in the output I now mention the specific files where the info can be found. However, if you want to go back to the old situation giving 'outall y' makes huge output files again.
Cheers,
  Arjan

**Comment by avoyles** [comment]
Hi Arjan,
Fantastic!  can confirm the spectra are now outputting properly - I had indeed seen the shift towards the new output format, and absolutely love it!!  Thanks so much for the quick patch!
